nodeLinker: node-modules

npmScopes:
  caffeinebounce:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_TOKEN-}"

packageExtensions:
  "@react-email/components@*":
    peerDependencies:
      react-dom: "*"
