npmScopes:
  caffeinebounce:
    # Read the auth token from the GITHUB_TOKEN environment variable
    # Create a `.env` file with GITHUB_TOKEN or set it in your environment
    npmAuthToken: ${GITHUB_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"
