nodeLinker: node-modules

npmScopes:
  caffeinebounce:
    npmAuthToken: "${GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@react-email/components@*":
    peerDependencies:
      react-dom: "*"
